// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20180711092211_newFields")]
    partial class newFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.DayOfBusy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CurrentDay");

                    b.Property<bool>("CurrentWeek");

                    b.Property<string>("Holder");

                    b.Property<string>("Note");

                    b.Property<int?>("RoomId");

                    b.Property<int>("ScheDayId");

                    b.Property<TimeSpan>("TimeOfBusy");

                    b.Property<TimeSpan>("TimeOfFree");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("ScheDayId");

                    b.ToTable("DaysOfBusy");
                });

            modelBuilder.Entity("WebApi.Models.MeetingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("MeetingRooms");
                });

            modelBuilder.Entity("WebApi.Models.ScheDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("ScheDays");
                });

            modelBuilder.Entity("WebApi.Models.DayOfBusy", b =>
                {
                    b.HasOne("WebApi.Models.MeetingRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("WebApi.Models.ScheDay", "ScheDay")
                        .WithMany("Chunks")
                        .HasForeignKey("ScheDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
